
package pe.gob.segdi.wsentidad.ws;

import java.util.List;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PcmIMgdEntidadPortType", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PcmIMgdEntidadPortType {


    /**
     * 
     * @param sidcatent
     * @return
     *     returns java.util.List<pe.gob.segdi.wsentidad.ws.EntidadBean>
     */
    @WebMethod(action = "getListaEntidad")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaEntidad", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "pe.gob.segdi.wsentidad.ws.GetListaEntidad")
    @ResponseWrapper(localName = "getListaEntidadResponse", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "pe.gob.segdi.wsentidad.ws.GetListaEntidadResponse")
    public List<EntidadBean> getListaEntidad(
        @WebParam(name = "sidcatent", targetNamespace = "")
        int sidcatent);

}
